version: '3.9'
services:
  app:
    build: .
    container_name: todo-app
    environment:
      - POSTGRES_URI=postgres://postgres:postgres@db:5432/apps?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: todo-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apps
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: todo-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
